# Generated by Django 4.1.4 on 2023-01-01 18:28

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import museumore.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Gallary',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50, unique=True)),
                ('password', models.CharField(max_length=20, validators=[museumore.models.numberValidator, django.core.validators.MinLengthValidator(8)])),
                ('name', models.CharField(max_length=50)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('image', models.ImageField(null=True, upload_to='')),
                ('address', models.TextField(null=True)),
                ('contact', models.IntegerField(null=True)),
                ('description', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('audio', models.FileField(upload_to='audios/')),
                ('augmented_video', models.FileField(upload_to='augmented_videos/')),
                ('extra_video', models.FileField(upload_to='extra_videos/')),
                ('gallary', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='item_gallary', to='museumore.gallary')),
            ],
        ),
    ]
