# Generated by Django 4.1.4 on 2022-12-29 19:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museumore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallary',
            name='address',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='gallary',
            name='contact',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='gallary',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='gallary',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
