# Generated by Django 4.1.4 on 2022-12-27 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museumore', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='gallary_id',
        ),
        migrations.RemoveField(
            model_name='item',
            name='video',
        ),
        migrations.AlterField(
            model_name='item',
            name='augmented_video',
            field=models.FileField(upload_to='augmented_videos/'),
        ),
    ]
