# Generated by Django 4.1.4 on 2023-01-06 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museumore', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='target_image',
            field=models.FileField(default='myfiles/default.docx', upload_to='target_images/'),
        ),
    ]
