# Generated by Django 4.1.4 on 2023-01-17 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museumore', '0002_alter_item_target_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='gallary',
        ),
        migrations.AddField(
            model_name='item',
            name='gallary_id',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gallary',
            name='address',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='gallary',
            name='contact',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='gallary',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='gallary',
            name='image',
            field=models.ImageField(null=True, upload_to='gallary_profile/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='audio',
            field=models.FileField(null=True, upload_to='audios/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='augmented_video',
            field=models.FileField(null=True, upload_to='augmented_images_or_videos/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='extra_video',
            field=models.FileField(null=True, upload_to='extra_videos/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='target_image',
            field=models.FileField(null=True, upload_to='target_images/'),
        ),
    ]
