# Generated by Django 4.1.4 on 2022-12-30 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museumore', '0002_alter_gallary_address_alter_gallary_contact_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallary',
            name='email',
            field=models.EmailField(max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name='gallary',
            name='username',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
