# Generated by Django 4.1.4 on 2023-01-21 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museumore', '0003_remove_item_gallary_item_gallary_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='target_index',
            field=models.IntegerField(default=0),
        ),
    ]
