# Generated by Django 4.1.4 on 2023-02-05 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museumore', '0004_item_target_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='target_image',
            field=models.ImageField(null=True, upload_to='target_images/'),
        ),
        migrations.AlterField(
            model_name='item',
            name='title',
            field=models.TextField(),
        ),
    ]
