# Generated by Django 4.1.4 on 2023-03-02 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('museumore', '0011_alter_item_target_data'),
    ]

    operations = [
        migrations.CreateModel(
            name='TargetFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.FileField(null=True, upload_to='target_file/')),
            ],
        ),
    ]
